name: Build and test
'on':
  pull_request
  push:
    branches:
      - master
jobs:
  build_and_test:
    runs-on:
      ubuntu-latest
      windows-latest
      macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm run ci
